export const FETCH_TODOLIST_DATA = 'todolist/FETCH_TODOLIST_DATA';
export const RECEIVE_TODOLIST_DATA = 'todolist/RECEIVE_TODOLIST_DATA';
export const TODOLIST_DATA_NOT_FOUND = 'todolist/TODOLIST_DATA_NOT_FOUND';
export const CREATE_TODOLIST_ITEM = 'todolist/CREATE_TODOLIST_ITEM';
export const DELETE_TODOLIST_ITEM = 'todolist/DELETE_TODOLIST_ITEM';
export const UPDATE_TODOLIST_ITEM = 'todolist/UPDATE_TODOLIST_ITEM';