export const FETCH_EVENT_DATA = 'event-data/FETCH_EVENT_DATA';
export const RECEIVE_EVENT_DATA = 'event-data/RECEIVE_EVENT_DATA';
export const EVENT_DATA_NOT_FOUND = 'event-data/EVENT_DATA_NOT_FOUND';
export const SAVE_EVENT_DATA = 'event-data/SAVE_EVENT_DATA';
export const FETCH_EVENT_HISTORY_DATA = 'event-data/FETCH_EVENT_HISTORY_DATA';
export const RECEIVE_EVENT_HISTORY_DATA = 'event-data/RECEIVE_EVENT_HISTORY_DATA';
export const EVENT_HISTORY_DATA_NOT_FOUND = 'event-data/EVENT_HISTORY_DATA_NOT_FOUND';
